#ddev-generated

COPY start-vnc.sh /usr/local/bin/start-vnc.sh
RUN chmod +x /usr/local/bin/start-vnc.sh

COPY start-vnc.conf /etc/supervisor/conf.d/start-vnc.conf

# Expose VNC and noVNC ports
EXPOSE 5901 6080

