#ddev-generated
webimage_extra_packages:
  - tigervnc-standalone-server
  - openbox 
  - tigervnc-common
  - x11vnc
  - xdotool
  - fluxbox
  - x11-xserver-utils
  - xterm
  - xfonts-base
  - tigervnc-tools
  - x11-utils 
